### ISSUE TITLE
lo_cpp.h include of <cassert> in the middle of namespace causes build failures

### ISSUE THREAD

**Issue by cme** [radarsat1/liblo#100]
lo_cpp.h has a ```#include <cassert>``` inside the ```lo``` namespace declaration, which results in the necessary declarations being inaccessible to anything that includes lo_cpp.h before its own inclusion of ```<cassert>``` due to the preprocessor multiple-inclusion guard.

I've submitted #99 as a suggested fix, moving the necessary ```#include``` to the top of the file and leaving the rest of the declarations in place.

**Comment by radarsat1** [comment]
Thank you!
