### ISSUE TITLE
bugs: unexpected behavior when adding multiple different methods with the same address pattern

### ISSUE THREAD

**Issue by DocSunset** [radarsat1/liblo#116]
I noticed this while working on libmapper/libmapper#40. 

When a libmapper device is created, the network calls `lo_server_add_method` twice, with address patterns for `/name/registered` and `/name/probe`, passing the device as user data (see `network.c:mpr_net_add_dev`). If you then make a second device using the same network object, `lo_server_add_method` gets called again with the same address patterns, passing the second device as user data. I expected liblo to call the handler twice, one time per device, passing the appropriate device as user data each time. Instead, in `server.c:dispatch_method` (I believe on line 2023) liblo breaks out of the for loop iterating over callback methods and the second matching callback never gets called back.

I've circumvented the issue in libmapper by registering one callback passing the graph as user data, and then iterating over local devices and calling the old callback for each of them, but this behaviour still caught me off guard and kept me debugging for longer than I would like to admit.

It is arguable whether the behaviour I expected is actually reasonable or not. I feel it is, and that liblo should be corrected to behave as I expected. I would also understand if it were decided that multiple callbacks assigned to the same address pattern is inappropriate, in which case I would be satisfied with documentation of this restriction being added somewhere.

**Comment by DocSunset** [comment]
Looks like this general theme also leads to segmentation faults. If you `lo_server_add_method` two methods with the same address pattern, then later try to `lo_server_del_method` both of them, the second call causes a segfault. Not sure about the details.

**Comment by radarsat1** [comment]
Hi @DocSunset, if the method handler returns 0 then this stops the propagation of the message to further handlers.  If the method returns 1, then the next handler will be called.  The order is not really guaranteed, but in practice it will be in the order that they are added, since the method list is a simple linked list that is traversed during dispatch.

The docs for the `lo_method_handler` type states:
```
 * The return value tells the method dispatcher whether this handler
 * has dealt with the message correctly: a return value of 0 indicates
 * that it has been handled, and it should not attempt to pass it on
 * to any other handlers, non-0 means that it has not been handled and
 * the dispatcher will attempt to find more handlers that match the
 * path and types of the incoming message.
```

Does this behaviour (returning 1 from your handler) solve the problem with libmapper?  If not, let's see what we can come up with.

Regarding the crash with `lo_server_del_method`, so far I have been unable to reproduce it.  I tried adding two method handlers with the same signature and then calling `lo_server_del_method` but it did not segfault for me.  Can you give a small modification to `example_server.c` that would reproduce it?

**Comment by DocSunset** [comment]
Aha. My apologies for exposing my unfamiliarity with the API and not more thoroughly reading the docs. When I get back to work on Monday, I’ll try changing the return code in my branch of libmapper and see how it goes. 

I’m seeing the segfault running libmapper `test/test.c` on my shared mpr_net feature branch. I’ll see if I can give a better minimum example for the segfault on Monday. Please stand by!

**Comment by radarsat1** [comment]
It's no problem at all ;)  Definitely interested in any improvements or providing any needed clarity to the docs.

**Comment by DocSunset** [comment]
Changing the return code to a non-zero value worked perfectly. I'm looking into the segfaults now.

**Comment by DocSunset** [comment]
Well, it is with much embarrassment that I must admit the segfaults appear to be originating in my own buggy code; the server was being used after being freed. The error signal was just waiting to be thrown until deep inside of a liblo method, so I mistakenly assumed liblo was to blame. Oops.

My only suggestion at this point is to maybe consider adding named constants for `lo_method_handler` return codes, in the fashion of `EXIT_FAILURE` and `EXIT_SUCCESS` found in `stdlib.h`. Overall though it looks like this issue is all on me.

**Comment by radarsat1** [comment]
Great, glad you found the problem!

Agreed, return codes could be documented more obviously, at least in the examples, and named constants would go a long way towards that.  Thanks for the suggestion.
