### ISSUE TITLE
Unable to get message's source address with UNIX protocol

### ISSUE THREAD

**Issue by jean-emmanuel** [radarsat1/liblo#121]
Hi,
When using unix sockets, I'm unable to retrieve the message's source address, is this a limitation with this protocol or could it be a blind spot in liblo's implementation ? OSC over unix socket has been in my experience the most reliable and the fastest protocol, it would be perfect if it wasn't for this caveat :)

**Comment by jean-emmanuel** [comment]
I've created PR #122 as a fix proposal

**Comment by radarsat1** [comment]
Merged!
