### ISSUE TITLE
Issues using liblo on WSL Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by g-l-i-t-c-h-o-r-s-e** [radarsat1/liblo#124]
I get this error message when trying to use an [application ](http://eca.cx/ecasound/) that has [OSC support.](https://ecasound.seul.org/ecasound/Documentation/ecasound_osc_interface.txt)
I've compiled version 0.28, 0.29 and 0.30 from source, as well as tried the available repo package `liblo-devel` with no luck.

**liblo server error -8 in path (null): Servname not supported for ai_socktype**
Could not start a server with port url, multicast group osc.udp://:9000

I can recreate this error with oscdump, by incorrectly using it like so:
`oscdump test osc.udp://:9000`

**Comment by radarsat1** [comment]
Looking at the code I don't see that ecasound is doing anything particularly weird, it just calls `lo_server_thread_new` with a port number (`port_str`).  When you run it, what is the value of `port_str`?

As for your example, it's the wrong syntax for `oscdump`, so not surprising that it doesn't work.  It only takes one argument, either the port number or a URL.  Not sure what `test` is doing there.
