### ISSUE TITLE
Server using TCP+SLIP?

### ISSUE THREAD

**Issue by fferri** [radarsat1/liblo#127]
There is a method to enable slip encoding for outgoing messages (`int lo_address_set_stream_slip(lo_address t, int enable)` / `int lo::Address::set_stream_slip(int enable)`).

However it seems there is no corresponding method for the server to decode messages using slip.

I have an existing server that does bi-directional communication using TCP+SLIP. Sending from liblo to the server works fine when enabling slip. But I can't receive any message from the server to liblo.

Am I missing something?

E.g. in the following example, none of the method handlers is ever called. But I'm 100% sure the reference server is sending the messages.
```
#include <iostream>
#include <thread>
#include <chrono>

using std::cout;
using std::endl;

#include <lo/lo.h>
#include <lo/lo_cpp.h>

int main(int argc, char *argv[])
{
    lo::ServerThread st(9000, LO_TCP, [](int e, const char* s, const char *t){});
    if(st.is_valid()) {
        st.set_callbacks([&st](){cout << "Thread init: " << static_cast<void*>(&st) << endl;},
                         [](){cout << "Thread cleanup." << endl;});
        cout << "server URL: " << st.url() << endl;

        st.add_method("/server/socket", "i",
                          [&](lo_arg **argv, int argc)
                          {cout << "/server/socket" << argv[0]->i << endl;});
        st.add_method("/chat/listrequest", "i",
                          [&](lo_arg **argv, int argc)
                          {cout << "/chat/listrequest" << argv[0]->i << endl;});
        st.start();

        lo::Address a("localhost", "3025", LO_TCP);
        a.set_stream_slip(1);
        a.set_tcp_nodelay(1);

        // ask for our socket number:
        if(a.send_from(st, "/s/server/socket", "") == -1) {
            cout << "send_from error" << a.errstr() << endl;
        }

        // send a chat message
        if(a.send("/b/chat/msg", "ss", "c++client", "hi") == -1) {
            cout << "send error" << a.errstr() << endl;
        }
    } else {
        cout << "error: cannot create server" << endl;
    }

    while(true)
        std::this_thread::sleep_for(std::chrono::seconds(1));

    return 0;
}
```

**Comment by radarsat1** [comment]
The function [detect_slip](https://github.com/radarsat1/liblo/blob/master/src/server.c#L992) in `server.c` is supposed to detect an incoming SLIP stream.  It's fairly heuristic though.  If it's not working for you, can you suggest a change?

Unfortunately I don't have your "existing server" so it's hard for me to debug this.  Fwiw I did modify your program to send messages to itself (to 9000 instead of 3025) and the program does seem to work whether `a.set_stream_slip(1)` is called or not.

**Comment by radarsat1** [comment]
Just merged a PR that should fix this.  Actually found quite a few bugs in the TCP implementation, so thanks.  I tested it against the mentioned pd patch.  I had to change your code to receive the message `"/s/server/socket"` but it seems to work now.  Please re-open if the problem persists!

**Comment by fferri** [comment]
I tested this again, but still cannot get server replies with liblo.
Here's what I did:
- fetched liblo master (so I have commits up to Sun Sep 11 00:59:54 2022 +0200), built it (`./autogen.sh && make`)
- compiled my testcase (`c++ -std=c++11 -Iliblo test.cpp -Lliblo/src/.libs -llo`)
- run netpd-server locally (using netpd macOS app and [netpd-server](https://github.com/reduzent/netpd-server); I found that [tcpsocketserver] is missing so I have to install iemnet, mrpeach, and also change [tcpsocketserver] to [net/tcpsocketserver]... perhaps @reduzent can clarify which of these steps is needed and which not?) (alternatively, the official netpd.org server could be used, same result)

In my test I only had to change

        a.set_stream_slip(1);

to:

        a.set_stream_slip(LO_SLIP_SINGLE);
        //a.set_stream_slip(LO_SLIP_DOUBLE);

(either of the two, none worked).

Like the previous time, I see the netpd-server receiving the messages and sending the replies, but the client gets no replies.
I'm not sure if there is some issue with my liblo-based client.

For reference, I wrote another OSC-over-SLIP-over-TCP client, from scratch, using Qt's QTcpSocket only, and this one works well with netpd-server. You can find my implementation [here](https://github.com/fferri/QNetPd/blob/master/osc.cpp).

When you say you had to change my liblo-based client, can you explain what the change is about?

P.S. I have no option to reopen this issue.

**Comment by reduzent** [comment]
>     * run netpd-server locally (using netpd macOS app and [netpd-server](https://github.com/reduzent/netpd-server); I found that [tcpsocketserver] is missing so I have to install iemnet, mrpeach, and also change [tcpsocketserver] to [net/tcpsocketserver]... 

Oh, thanks for pointing that out. My goal is to only have iemnet as a dependency and leave mrpeach out. I'll make sure that all the abstractions are included.

**Comment by reduzent** [comment]
@fferri I'm afraid, I'm not of great help here. I'm not familiar with the implementations of OSC in the externals used by netpd and I'm also not a C(++) coder. 

One of the first things to check is if the delimitation with SLIP works correctly. From what I remember, there exist slightly varying flavors of the protocol. Some put the `0xC0` only at the end of the frame, some others (like [slipenc] used in netpd-server) put it at the start and the end of the frame. Maybe liblo and [slipenc] from slip disagree on that?

It seems that [slipdec] deals with both. However, [[https://en.wikipedia.org/wiki/Serial_Line_Internet_Protocol|Wikipedia]] seems to suggest, that actually only one `0xC0` should be used at the end of each frame.

**Comment by radarsat1** [comment]
> When you say you had to change my liblo-based client, can you explain what the change is about?

I mean that the server was responding with a message but not your message your client was programmed to receive.  You programmed it to receive `"/server/socket"` but I saw that the server was actually replying with `"/s/server/socket"`. With this change, (and my recent fixes to liblo), I was able to receive a message from the PureData program.

**Comment by radarsat1** [comment]
@reduzent liblo supports both varieties of the protocol.  it tries to sniff which one is in use at the first message received.

**Comment by reduzent** [comment]
> > When you say you had to change my liblo-based client, can you explain what the change is about?
> 
> I mean that the server was responding with a message but not your message your client was programmed to receive. You programmed it to receive `"/server/socket"` but I saw that the server was actually replying with `"/s/server/socket"`. With this change, (and my recent fixes to liblo), I was able to receive a message from the PureData program.

Ah, I see. When sending a message, the netpd-protocol uses the first element of the OSC path as the recipient ID (`s` = server, `b` = broadcast, int numbers identify a client). Similarly,  a message received from the server has the sender id in the first element of the OSC path. Also here, `s` means server. This is done to let clients know about the origin of a message.

For a message `/s/server/socket`, you'll get back a message from the server, thus the path is `/s/server/socket`.

**Comment by fferri** [comment]
> > When you say you had to change my liblo-based client, can you explain what the change is about?
> 
> I mean that the server was responding with a message but not your message your client was programmed to receive. You programmed it to receive `"/server/socket"` but I saw that the server was actually replying with `"/s/server/socket"`. With this change, (and my recent fixes to liblo), I was able to receive a message from the PureData program.

Oh, right! That is a bug in my liblo-based test case. After changing the address to `/s/server/socket` (and using latest liblo) it works.

**Comment by fferri** [comment]
And it seems to work both with `LO_SLIP_SINGLE` and `LO_SLIP_DOUBLE`, so the SLIP flavour doesn't seem to be an issue here.

**Comment by radarsat1** [comment]
Excellent! Glad to hear. Bug was serious enough that I am thinking towards a new release soon.
