### ISSUE TITLE
Tag a new version?

### ISSUE THREAD

**Issue by bramtayl** [radarsat1/liblo#144]
It would be great to get a version that includes #123, because the old installed find module doesn't work on windows

**Comment by stekyne** [comment]
@radarsat1 hey it would be great if this could be done

**Comment by JohannesLorenz** [comment]
Over at [https://github.com/zynaddsubfx/zynaddsubfx](zynaddsubfx), we also need a new version in order to solve MSVC build issues. We would appreciate it a lot.

**Comment by radarsat1** [comment]
Hi guys, understood but things are a bit blocked on the fact that the Mac github actions are hanging for no apparent reason.  Anyway I could ignore that and I'll try to find a moment to put together a release, but it's hard for me to find time these days.  Please see issue #150 if you are interested in helping out.
