### ISSUE TITLE
Robustness in case of missing OSC Type Tag String

### ISSUE THREAD

**Issue by showlabor** [radarsat1/liblo#17]
Hi,
I've been playing around with the Behringer's X32-Edit software for controlling the X32 series digital mixers (in preparation of a possible purchase). oscdump shows "liblo server error 9902 in path /info: Invalid message received". According to the documentation[1] of their OSC protocol the message send to info /info should be nil but obviously the Type Tag String is missing in their implementation.

The OSC 1.0 specs[2] say about it:
"OSC Messages
An OSC message consists of an OSC Address Pattern followed by an OSC Type Tag String followed by zero or more OSC Arguments.

Note: some older implementations of OSC may omit the OSC Type Tag string. Until all such implementations are updated, OSC implementations should be robust in the case of a missing OSC Type Tag String."

So, obviously liblo is not robust against missing OSC Type Tag Strings. It would be great if missing types could just be handled like 'nil' types so that liblo is able to talk with other (yes, I know they are wrong) implementations.

Thanks and kind regards,
Felix

[1] http://www.behringer.com/assets/X32_OSC_Remote_Protocol.pdf
[2] http://opensoundcontrol.org/spec-1_0

**Comment by showlabor** [comment]
OK, I'm late(*), sorry ...
liblo chokes on packages (from tcpdump) like these:

13:50:30.895414 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto UDP (17), length 36)
    nexus7v2013.fritz.box.36956 > 255.255.255.255.10024: [udp sum ok] UDP, length 8
        0x0000:  4500 0024 0000 4000 4011 c7e4 c0a8 b23c  E..$..@.@......<
        0x0010:  ffff ffff 905c 2728 0010 c894 2f69 6e66  .....\'(..../inf
        0x0020:  6f00 0000 0000 0000 0000 0000 0000       o.............
13:50:33.897664 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto UDP (17), length 36)
    nexus7v2013.fritz.box.36956 > 255.255.255.255.10024: [udp sum ok] UDP, length 8
        0x0000:  4500 0024 0000 4000 4011 c7e4 c0a8 b23c  E..$..@.@......<
        0x0010:  ffff ffff 905c 2728 0010 c894 2f69 6e66  .....\'(..../inf
        0x0020:  6f00 0000 0000 0000 0000 0000 0000       o.............

oscdump spits out those messages:

./oscdump 10024
liblo server error 9902 in path /info: Invalid message received
liblo server error 9902 in path /info: Invalid message received

(*) I stepped away from the X32 rack last year and decided in favor of a X Air XR18 which I received only lately.

**Comment by radarsat1** [comment]
Hi, I don't have a lot of time to look into it right now, but to put
you on the right path:

I think you might try messing with lo_message_deserialize(),
specifically line 904 in message.c, where it says "// types"

You can see that is where it generates a failure when the type string
is missing.

Steve

**Comment by showlabor** [comment]
I have looked into the messages received that trigger the error message: They simply are invalid OSC messages. This has nothing to do with the above mentioned robustness in case of missign type tag string.
Sorry for the noise. Closing this issue.
