### ISSUE TITLE
Difficulty configuring on Ubuntu 14

### ISSUE THREAD

**Issue by Space-Ed** [radarsat1/liblo#24]
I'm trying to set up the osc-midi bridge on ubuntu for TouchOSC using pyliblo. I'm having some difficulty with configuration. 

autoconf gives

configure.ac:29: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:30: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:33: error: possibly undefined macro: AC_ENABLE_STATIC
configure.ac:34: error: possibly undefined macro: AC_ENABLE_SHARED
configure.ac:53: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
configure.ac:54: error: possibly undefined macro: AM_PROG_LIBTOOL
configure.ac:55: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:112: error: possibly undefined macro: AM_CONDITIONAL

./configure gives

./configure: line 2240: AM_INIT_AUTOMAKE: command not found
./configure: line 2241: AM_MAINTAINER_MODE: command not found
./configure: line 2244: syntax error near unexpected token `no'
./configure: line 2244: `AC_ENABLE_STATIC(no)'

Guessing there is some build tool dependency that I'm missing

I will look into this issue. Help or tips much appreciated.

**Comment by fsateler** [comment]
It seems you are missing automake. Use the autogen.sh script instead of running autoconf manually

**Comment by Space-Ed** [comment]
Hey thanks, that worked a charm. 

perhaps this should be an instruction in INSTALL

**Comment by radarsat1** [comment]
Ah, true, but the INSTALL instructions are intended for tar releases, which contain a pre-generated "configure".  These days more people use it directly from git, so perhaps the instructions should be updated.  (The INSTALL instructions are generic.)

**Comment by radarsat1** [comment]
In the past it was generally understood that using the package from the repository was intended for developers of the package, while the tarball is intended for users of the package.  Times they are a-changin'
