### ISSUE TITLE
buildozer recipe.sh for android ?

### ISSUE THREAD

**Issue by stuaxo** [radarsat1/liblo#30]
I tried to send this to the mailinglist, but think it bounced..

Is there any chance of a recipe.sh for buildozer ?

It should be really similar to build/android-build.sh I just don't grok the android build stuff enough to port it - I guess the main difference is just using the toolchain etc that buildozer passes in via env vars ?

**Comment by radarsat1** [comment]
Sorry this is old.  But, I have no idea what buildozer is.  I'm not up to date on Android stuff. If you want to make a PR then I'll consider it, but for now I'll close this.

**Comment by stuaxo** [comment]
Sure:  buildozer is a kivy thing (python) you have a script very similar to build/android-build.sh, with a couple of differences.

The main difference IRCC, seems to be it sets some environment variables for the ndk version etc...  though I don't know much more than that.

Next time I look at kivy (that might be a while), I'll have another look at this.

**Comment by radarsat1** [comment]
Ok.  I wouldn't be surprised if the android build script is out of date, and I realize it's probably not the best way to support Android, but I don't have a good means to test it at the moment.  Sometime in the near future I'll likely be doing some Android stuff again, so at that time I might be able to look at such tools.  In the meantime, if you have a PR, I'll gladly consider it.
