### ISSUE TITLE
varargs test fails on Windows and Linux

### ISSUE THREAD

**Issue by johnty** [radarsat1/liblo#35]
It looks like [this test ](https://github.com/radarsat1/liblo/blob/master/src/testlo.c#L447) is failing on both Windows and Linux. Recreated the same error on the following platforms:

- XUbuntu32 running in Virtualbox on Mac (10.11)
- Raspberry Pi 2 (Debian Jessie)
- Windows 8.1 x64 in MinGW, (but possibly compiling 32 bit - will double check this later today...)

Since as you mentioned in the libmapper thread that it might be a 32/64bit variadic issue, I will give it a shot on 64 bit systems and see if it works.

----

For example, output from XUbuntu32:

```
  == test_varargs() ==
passed test_varargs (a, "/lotsofformats", "fisbmhtdSccTFNI", 0.12345678f, 123, "123", btest, midi_data, 0x0123456789abcdefULL, tt, 0.9999, "sym", 'X', 'Y', LO_ARGS_END) == 0
  == test_varargs() ==
liblo error: lo_send, lo_message_add, or lo_message_add_varargs called with mismatching types and data at
testlo.c:458, exiting.
lo_message_add_varargs returned -2
passed test_varargs(a, "/lotsofformats", "f", 0.12345678f, 123, "123", btest, midi_data, 0x0123456789abcdefULL, tt, 0.9999, "sym", 'X', 'Y', LO_ARGS_END) != 0
  == test_varargs() ==
liblo error: lo_send or lo_message_add called with invalid symbol pointer for arg 9, probably arg mismatch
at testlo.c:458, exiting.
lo_message_add_varargs returned -2
passed test_varargs (a, "/lotsofformats", "fisbmhtdSccTFNI", 0.12345678f, 123, "123", btest, midi_data, 0x0123456789abcdefULL, tt, 0.5, LO_ARGS_END) != 0
passed lo_message_add(m, "fisbmhtdSccTFNI", 0.12345678f, 123, "123", btest, midi_data, 0x0123456789abcdefULL, tt, 0.9999, "sym", 'X', 'Y') == 0
  == test_pattern() ==
```

**Comment by radarsat1** [comment]
Ok I was able to reproduce this by,

    apt-get install gcc-multilib g++-multilib libc6-dev-i386

on Ubuntu and compiling with `CFLAGS=-m32` and `CXXFLAGS="-m32 -std=c++11"`.

**Comment by radarsat1** [comment]
The issue appears to be with the recent PR #34, which I clearly didn't test enough. I'll see if I can fix it.

**Comment by radarsat1** [comment]
I fixed the problem, just a mistake related to checking a test string that was modified by that commit.  I didn't get that mismatching types error, in fact, can you verify that the current master (c2b871863) is working?

**Comment by johnty** [comment]
great - got the linux versions working. will check out the windows one when i get home!

**Comment by radarsat1** [comment]
Great!
