### ISSUE TITLE
Failure to send large messages over TCP

### ISSUE THREAD

**Issue by anonymouse64** [radarsat1/liblo#38]
Hi,
I am attempting to use liblo to send some large messages (binary data of images really), and I'm running into some issues with larger images. Specifically the following code fails with `failSize` set to 32753, but works properly when using a message size of 32752. 

```

//for liblo
#include "lo/lo.h"

//for printf
#include <stdio.h>


int main(int argc, char ** argv)
{

    long long int failSize = 32753;

    const char * host = "localhost";

    const char * port = "7000";

    const char * path = "/test2";

    //make an address object
    lo_address destAddr = lo_address_new_with_proto(LO_TCP,host,port);

    //make a new message
    lo_message message = lo_message_new();

    //allocate memory for the data
    unsigned char * data = (unsigned char *) calloc(failSize,sizeof(unsigned char));

    //fill the array with test data
    int index = 0;
    for(index = 0; index < failSize; index++)
        data[index] = index;

    lo_blob myBlob = lo_blob_new(failSize,(void *)data);

    //put the blob into the message
    lo_message_add_blob(message,myBlob);

    //free the blob
    lo_blob_free(myBlob);

    //free our copy of the data too
    free(data);

    //send the message
    int sendResult = lo_send_message(destAddr,path,message);
    if(sendResult < 0)
    {
        //send failed
        printf("failed to send message\n");
        printf("errno : %s (%d) \n",strerror(lo_address_errno(destAddr)),lo_address_errno(destAddr));
        printf("message length was : %lld\n",failSize);
    }
    else
    {
        printf("sent message successfully\n");
    }

    //free the message
    lo_message_free(message);
}
```

Running this on my machine produces:

```
failed to send message
errno : Not a STREAM (99) 
message length was : 32753
```

I was under the impression that with TCP there wasn't an upper limit on message sizes? I am only sending one argument, a binary blob.

**Comment by radarsat1** [comment]
The default internal limit is LO_MAX_MSG_SIZE = 32768, so with header information this seems to correspond.  Try using `lo_server_max_msg_size()`.

Note that it's consider a limit use case to send very large messages using OSC.

**Comment by anonymouse64** [comment]
Is the define you mention a limit on the incoming messages, or outgoing messages?
I am not worried about memory usage or being open to some sort of DDOS attack, as this is just on a local machine.

**Comment by radarsat1** [comment]
I believe it's not a sending limit when using TCP, but it's used for incoming buffers.  However, in the TCP implementation the buffers are dynamic if I remember correctly, so they'll double their allocation until a whole message is received.  I don't have time to test seriously right now, so please try and report back!  No limit will be imposed if you set max_msg_size to -1.

I wanted to link to the documentation but I see the online doxygen is out of date!  Must update it, sorry.

**Comment by anonymouse64** [comment]
Okay, I'll give it a shot. Thanks for the information.

**Comment by anonymouse64** [comment]
Here's what I have tried:

1. I rebuilt liblo, defining `LO_MAX_MSG_SIZE` as `1073741824`
2. I made a new server and called `lo_server_max_msg_size(server, -1);` with it.

I can now get messages up to around 65000 successfully sent and received, but past that the server doesn't receive the messages. Can you think of anything else that may be arbitrarily limiting it? I have also tried using `lo_server_max_msg_size(server, 2147483647);` as well, but still any messages above around 65000 don't make it to the server.

The client can still send fairly large messages (around 512000 bytes it still works most of the time, some transient errors, but acceptable I would think above 95% of the time), but for above a certain size it fails with:
```
failed to send message
errno : Broken pipe (32) 
message length was : 1024000
```
or sometimes 
```
failed to send message
errno : Protocol wrong type for socket (41) 
message length was : 1024000
```

Is this just too much for liblo to handle (on the sending side)?

**Comment by radarsat1** [comment]
Yeah I don't know if this has ever been stress tested.  It's rather odd to use OSC this way, I would think HTTP would be a better protocol for file transfer.  Personally I don't think it's good application design to treat the TCP and UDP transports significantly differently, as I would think you'd want to be able to switch between them easily for compatibility with other applications.  But in any case, if you want to test the sending and receiving separately, I guess crafting a payload and sending it using netcat ("nc") would be the way to go.  Similarly using nc for dumping a TCP received stream to a file.

**Comment by anonymouse64** [comment]
Okay, yeah I know it's a very odd use case, but I appreciate the advise anyways. If I come across an actual bug somewhere that is preventing large messages that should/could be fixed, I will reopen the issue, but in the meantime I'll do some testing to see what I can find out.

**Comment by radarsat1** [comment]
I don't mind leaving the issue open if it's truly not working ;)  I'll have time to look into it eventually.
However, one thing to keep in mind is that once liblo allocates a buffer large enough for a message, it never shrinks it again...
so this is partly a design/security issue.  We should do the right thing, but it's not totally clear to me.  I certainly don't mind the idea of liblo being able to handle this situation, even if it's not a normal use case.
