### ISSUE TITLE
Building in Visual Studio for 64-bit architecture?

### ISSUE THREAD

**Issue by lathertonj** [radarsat1/liblo#45]
Hi,

Is it possible to use the premake4 build flow to generate a Visual Studio project that will build liblo for Windows for a 64-bit architecture?

Apologies if I've missed something obvious, but the premake lua file seems pretty specialized to 32-bit windows. I've never developed for Windows before and I'm using an environment that only supports building via Visual Studio.

Thanks!

**Comment by radarsat1** [comment]
I don't see what in premake4.lua is specialized to 32-bit, but I guess the answer is to change whatever that is to something else ;)  Sorry, don't have windows here for testing, so I can't help much unfortunately.

**Comment by lathertonj** [comment]
Ok, thanks for your lightning-fast response anyway!

**Comment by radarsat1** [comment]
Closing so fast? :)  Did you solve the problem?

**Comment by lathertonj** [comment]
No, but I'll post an update here if I manage to. Figured there was no reason to keep it open since I'm not asking anything more of you, but you can re-open it if that more closely follows the conventions of this project!

**Comment by radarsat1** [comment]
Ok, good luck, do open an issue or re-open this one if you run into something, otherwise, PRs accepted!
