### ISSUE TITLE
Project is broken on MSVC

### ISSUE THREAD

**Issue by stekyne** [radarsat1/liblo#46]
https://github.com/radarsat1/liblo/commit/56cec7ec9ed35a722531e4e4b877a40b6f57a27e

This commit added the code "if (memcmp(&tt, &LO_TT_IMMEDIATE, sizeof(lo_timetag))==0) {" which fails to compile with Visual Studio. Any chance this could be looked at?

2>oscdump.c
2>C:\Users\skyne\Source\Repos\liblo\src\tools\oscdump.c(54): error C2102: '&' requires l-value
2>C:\Users\skyne\Source\Repos\liblo\src\tools\oscdump.c(88): error C2102: '&' requires l-value

**Comment by radarsat1** [comment]
Ah, good catch, it's because in Windows LO_TT_IMMEDIATE is a function returning a struct rather than being a literal struct. (Due to lack of support for the syntax used..)
I'll fix.
