### ISSUE TITLE
CMake build broken on Windows

### ISSUE THREAD

**Issue by stekyne** [radarsat1/liblo#49]
Hi guys, 

I submitted a pull request to get the CMake build working on Windows. Any chance this could be incorporated into the repo? 

As it stands, I can't really get it building with premake or cmake without manual modification to the produced solution files.

Thanks

**Comment by radarsat1** [comment]
Please close if it's fixed now.  I'd love to know actually.

**Comment by stekyne** [comment]
Hi, sorry should have responded to this sooner. It is building but I'm having trouble getting the cmake build to find pthreads. Other than that, it works fine. Can close this anyway

**Comment by radarsat1** [comment]
Sure, thanks for the CMake help, let me know (in a PR if possible) if you figure out any recommended changes due to pthreads issues.
