### ISSUE TITLE
Cpp_test is failing for MSVC

### ISSUE THREAD

**Issue by stekyne** [radarsat1/liblo#52]
Lot of build errors for this project. I'll need to spend more time figuring out where it's going wrong. There are a few fixes for header includes for the other tests as well but they seem to build fine after that.

**Comment by radarsat1** [comment]
Shit ok.  It needs to have C++11 turned on, which I tried to do.  I have no idea about the C++11 support in MSVC. Can you post some of the build errors?

**Comment by stekyne** [comment]
Ah just saw the cause I think. 
1>C:\Users\skyne\Source\Repos\liblo\lo/lo_cpp.h(215): error C2059: syntax error: ':'
1>C:\Users\skyne\Source\Repos\liblo\lo/lo_cpp.h(218): error C2059: syntax error: ':'
1>C:\Users\skyne\Source\Repos\liblo\lo/lo_cpp.h(221): error C2059: syntax error: ':'
1>C:\Users\skyne\Source\Repos\liblo\lo/lo_cpp.h(227): error C2059: syntax error: ':'
1>C:\Users\skyne\Source\Repos\liblo\lo/lo_cpp.h(230): error C2059: syntax error: ':'
1>C:\Users\skyne\Source\Repos\liblo\lo/lo_cpp.h(233): error C2059: syntax error: ':'
1>C:\Users\skyne\Source\Repos\liblo\lo/lo_cpp.h(379): error C2059: syntax error: ':'
1>C:\Users\skyne\Source\Repos\liblo\lo/lo_cpp.h(491): error C2059: syntax error: ':'

https://stackoverflow.com/questions/3319075/ternary-conditional-operator-behaviour-when-leaving-one-expression-empty
That idiom, where you leave a branch empty in the ternary operator, is not portable for msvc.

**Comment by radarsat1** [comment]
Ah, weird ok.  Actually yeah that is bad, I'm surprised both gcc and clang let that go. I don't remember doing it, I must have read that trick somewhere. I will fix.

**Comment by radarsat1** [comment]
Please let me know if it's fixed, thanks.

**Comment by stekyne** [comment]
It's working now, good work!

**Comment by stekyne** [comment]
I'll close the issue.
