### ISSUE TITLE
Pretty-print lo_args small numbers display

### ISSUE THREAD

**Issue by 7890** [radarsat1/liblo#58]
If a small value is sent as a float or double, it's likely that for instance oscdump using lo_arg_pp will display 0.00000.
Please see attached patch as a possible addition in lo_arg_pp_internal. 
-Displays small floats and doubles using scientific notation if the value is <=0.0001.
-Add missing (?) ' for symbol display. I wasn't 100% if it's missing or if a single ' helps to distinguish from the 'c' type. Since the typestring will indicate the difference, enclosing LO_SYMBOL with ' seemed sane.

[message.c.diff.txt](https://github.com/radarsat1/liblo/files/1330629/message.c.diff.txt)

**Comment by radarsat1** [comment]
Seems that this will print in scientific notation for all negative numbers if I am not mistaken?
In any case perhaps a simpler fix is to use %g instead of %f.  It would be nice if this could be an option although there is no global option mechanism right now.

**Comment by 7890** [comment]
oh. yes.. that's a bug haha. that was too quick.
%g "Use the shortest representation" sounds good

**Comment by radarsat1** [comment]
By the way I didn't fully read your first message. Your idea for distinguishing symbols is not too bad.  I'm not sure it's important to distinguish them but in principle it's interesting.  I have to think about it.  Technically there is no guarantee of full representation with the pretty-print functions, they are not intended to be a reversible "file format", but I've often thought that it would be interesting to think towards the goal of an OSC text format based on pretty-printed messages.  For instances, some contributors have expanded oscdump to emit code that can be used to play back a recorded sequence of OSC messages.

**Comment by 7890** [comment]
That's an interesting idea indeed, extending oscsend and oscdump for more use cases like binary dump, replay and so forth.
I guess we can totally scratch this "issue" for now and think more about it..

**Comment by radarsat1** [comment]
Yep, thanks!
