### ISSUE TITLE
cpp build issues with msvc2013

### ISSUE THREAD

**Issue by flv0** [radarsat1/liblo#61]
When building on msvc2013 using cmake the add_method template code fails with many errors of this kind:
```
C:\Users\swnc\Documents\development\src\liblo\lo/lo_cpp.h(521): error C2572: 'lo::Server::add_method' : redefinition of default parameter : parameter 4
C:\Users\swnc\Documents\development\src\liblo\lo/lo_cpp.h(515) : see declaration of 'lo::Server::add_method'
C:\Users\swnc\Documents\development\src\liblo\lo/lo_cpp.h(521): error C2535: 'lo::Method lo::Server::add_method(const lo::string_type,const lo::string_type,H &&,std::enable_if<std::is_same<unknown-type,int>::value,void>::type *)' : member function already defined or declared
C:\Users\swnc\Documents\development\src\liblo\lo/lo_cpp.h(515) : see declaration of 'lo::Server::add_method'
C:\Users\swnc\Documents\development\src\liblo\lo/lo_cpp.h(521): error C2548: 'lo::Server::add_method' : missing default parameter for parameter 4
```
and
```
C:\Users\swnc\Documents\development\src\liblo\src\cpp_test.cpp(66): error C2660: 'lo::Server::add_method' : function does not take 3 arguments
C:\Users\swnc\Documents\development\src\liblo\src\cpp_test.cpp(70): error C2660: 'lo::Server::add_method' : function does not take 3 arguments
```
It builds fine with msvc2017 so this is just for the record.

**Comment by radarsat1** [comment]
> It builds fine with msvc2017 so this is just for the record.

Good to know!  I would say the right thing would be to either ignore the condition or to configure CMake to not include this file if the compiler doesn't support it.  What do you think is easier?  In automake (and somehow in CMake) it's possible to execute the compiler on a bit of code (TRY_COMPILE) and change things accordingly, however for generating a Visual Studio project I imagine that doesn't work, so maybe just detecting known unsupported compilers is the way to go.

**Comment by radarsat1** [comment]
With 4aa1430b861c7de3ab38cbcffb63ee4eb32cdf3a you can turn off compiling C++ tests using `-DWITH_CPP_TESTS=OFF`.  Hopefully this is a satisfactory work-around.
