### ISSUE TITLE
Receiving OSC from TCP lo_address

### ISSUE THREAD

**Issue by tuscland** [radarsat1/liblo#64]
Hello,

`lo.h` has this comment for `lo_address_new_with_proto`:

```
 * Note: if you wish to receive replies from the target of this
 * address, you must first create a lo_server_thread or lo_server
 * object which will receive the replies. The last lo_server(_thread)
 * object created will be the receiver.
```

I am using `lo_server_new_with_proto`, and can't manage to receive data from the socket. My lo_server is first created (TCP, listens on port 8000), then the address (TCP, target listens on port 3032).

There is a first message to send to the target to subscribe for OSC TCP messages. I can see in the log of the client application that the subscription is made on a automatically assigned port (high number, e.g. 50462), which would indicate that the lo_address is not bound to the server port.

I looked at the source code but failed to find evidence that the last created lo_server is used as the TCP receiver. Is there something I am missing?

Thanks in advance,
Cam

**Comment by radarsat1** [comment]
Ah weird, could be a bug.  Any easy way to reproduce it?  e.g. small modification of example programs?  Anyway I'll take a look

**Comment by tuscland** [comment]
Thanks Stephen, I'll have a look at the examples as well.

**Comment by tuscland** [comment]
Hi Stephen,

After closer inspection, I can see I was incorrectly using `lo_message_send` instead of `lo_message_send_from`. This explains why my OSC server never received a reply.

Sorry for the noise.

Cam

**Comment by radarsat1** [comment]
Excellent!  Thanks for reporting, it will help future users.  Not sure if that interface is so obvious, I don't really like the part,

> The last lo_server(_thread) object created will be the receiver.

I recall now not liking this bit of non-thread-safe shared memory called `lo_client_sockets`.

Looking at the [code](https://github.com/radarsat1/liblo/blob/master/src/send.c#L450) now, I am wondering if this actually only applies to UDP sockets, it looks like for TCP  it always creates a socket and assigns it to the server provided through `lo_message_send_from`.  If there is no server provided, (i.e. `lo_message_send` was called) then it doesn't appear to do anything.
