### ISSUE TITLE
bogus loop when sending TCP/IP data

### ISSUE THREAD

**Issue by umlaeute** [radarsat1/liblo#82]
looking at how liblo deals with multiple results from `getaddrinfo()`, i see that in the case of UDP, you just try to send to each of the results until one succeeds.

however, there seems to be the same logic applied to the [TCP/IP case](https://github.com/radarsat1/liblo/blob/master/src/send.c#L518-L524), which i reproduce here for your own ease:

~~~C
do {
  ret = send(sock, data, len, MSG_NOSIGNAL);
  if (a->protocol == LO_TCP)
    ai = ai->ai_next;
  else
    ai = 0;
} while (ret == -1 && ai != NULL);
~~~

This looks slightly bogus to me, as you keep sending to the same socket `sock`: if you the send fails, you repeat sending to the very same address (the number of repeats is determined by the results from `getaddrinfo()`).

otoh, when creating the socket (`create_socket()`) you just try the very first result (but you could iterate over all until you find one that works)

**Comment by umlaeute** [comment]
this was triggered by a discussion at https://github.com/pure-data/pure-data/pull/577#issuecomment-493039331 ff

**Comment by radarsat1** [comment]
Thanks for the report, I'll look into as soon as I can.  Is there an easy way to test this?  As simple as two TCP connections to a server?

**Comment by radarsat1** [comment]
Thanks for the link, it would be great if you found a bug, there are still open issues with IPv6

**Comment by umlaeute** [comment]
the link won't tell you much (tzhe link should have gone in the other direction).

actually, i haven't found a way to *trigger* any problem. i haven't even looked for one (yet). i only had a look at the source code and couldn't help but notice that the loop is changing a variable that is nowhere used.

**Comment by umlaeute** [comment]
anyhow, this is what *should* trigger some extra (and bogus sending):

- make a nameservice entry that resolves to multiple hosts (e.g. `triplehost` resolving to `localhost` and some google nameservers, which I don't expect to expect to have the port open that I'm going to use)


~~~sh
$ cat | sudo tee -a /etc/hosts <<EOF
127.0.0.1     aliashost
8.8.8.8       aliashost
8.8.4.4       aliashost
# another (reachable) host in the local network
192.168.0.99 aliashost
EOF
$
~~~

- start a server on `localhost` listening on TCP:7777

~~~bash
$ nc -l -p 7777
~~~

- start another server on `192.168.0.99` listening on TCP:7777

- compile the following program

~~~C
#include <unistd.h>
#include "lo/lo.h"

int main(int argc, char *argv[])
{
    lo_address t = lo_address_new_with_proto(LO_TCP, "triplehost", "7777");
        lo_send(t, "/jamin/scene", "i", 1);
        sleep(10);
        lo_send(t, "/jamin/scene", "i", 2);
}
~~~

- run the above program
  - while it's sleeping (for 10 seconds), terminate the `nc` server on `localhost` (leave the one on 192.168.0.99 running)

- after wake up the program will attempt to send the 2nd message to `localhost`.
  - however, `localhost` is no longer available (`send()` returns *-1*)
  - the program will then make 3 more attempts
    - all attempts will fail immediately
    - however, no real attempt is made to send data to`192.168.0.99` (at least: no data is received by the still running `nc` server)

**Comment by radarsat1** [comment]
Yes, after staring at it I see that it is simply re-trying a number of times on failure.

It looks like that was added in commit eeb7b586233466.

Thanks for the extensive testing idea! I'll see if I can address it soon.  It seems the destination of send() is already determined when the socket is created, by connect(), so I guess either the loop over addrinfo should take place where connect() happens, or connect() should be done "on demand" when it is needed to `send()`.
