### ISSUE TITLE
Link to aiolo

### ISSUE THREAD

**Issue by elijahr** [radarsat1/liblo#91]
Hello, thanks so much to all the authors of this library, I'm looking forward to using it in my audio projects.

I've written Python [bindings for liblo](https://github.com/elijahr/aiolo) with some nice features that I think other folks would appreciate, such as asyncio support, a routing API, a publish-subscribe pattern, an extensive test suite, and both CPython and PyPy support.

Would you be open to adding a link to aiolo on the liblo homepage to help people find it?

**Comment by radarsat1** [comment]
Thank you, that's really cool!  Done!
