### ISSUE TITLE
Release 0.31

### ISSUE THREAD

**Issue by elijahr** [radarsat1/liblo#92]
Hello! I'm working on some routing features for [aiolo](https://github.com/elijahr/aiolo) that rely on e1532a8cbbbc98e066deda3d3c27de84dddd8b10 and e8408b67547934cb721ec09c4ad21bc11e596140 which haven't been released yet. Would you be willing to release 0.31 soon? Is there anything I can help with to make that happen?

**Comment by elijahr** [comment]
I also have a pull request with a fix for clang that would be nice to get in 0.31.

**Comment by radarsat1** [comment]
Sure, I see no problem with working towards a release.  Please keep testing and I'll get into it this week.

**Comment by radarsat1** [comment]
Whole bunch of pull requests merged and issues addressed, please test!

**Comment by elijahr** [comment]
My test suites in aiolo are passing using the latest from master, this is looking great. Thanks for working on this this week!

**Comment by radarsat1** [comment]
Release tagged in 840ed69b1d669a1ce587eb592746e3dff6985d76
